HELLOWORLD.PGM: helloworld-simple.pgm.rpgle

HELLOADV.MODULE: HELLOADV-Advanced_HelloWorld.rpgle
HELLOINC.MODULE: HELLOINC-Helloworld_using_copybook.rpgle 

HELLOADV.PGM: HELLOADV.MODULE
HELLOINC.PGM: HELLOINC.MODULE